name: ottergames
version: '1.0-SNAPSHOT'
main: org.antredesloutres.ottergames.Main
api-version: '1.21'
load: STARTUP

commands:
  otter:
    description: Une commande super simple pour le plugin Ottergames
    usage: /otter
